name: PxGraf CI

run-name: ${{ github.event_name == 'pull_request' &&
  format('CI for PR {0}', github.event.pull_request.number) || 
  format('CI for {0}', github.event.head_commit.message) }}

on:
  pull_request:
    branches:
    - dev
  push:
    branches:
    - main
    - test
    - dev
  workflow_dispatch:

# CI environment variable set to false to prevent warnings to cause the pipeline to fail
env: 
  CI: false

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet-version: ['8.x']
        node-version: ['21.x']
        configuration: [ 'Debug' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check project versions
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev' && github.actor != 'dependabot[bot]' }}
        run: bash .github/scripts/check_version_changes.sh

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./PxGraf.Frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./PxGraf.Frontend

      - name: Run frontend tests
        run: npm run test
        working-directory: ./PxGraf.Frontend

      - name: Set up dotnet 
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install backend dependencies
        run: dotnet restore

      - name: Build backend
        run: dotnet build --no-restore --verbosity normal --configuration ${{ matrix.configuration }}

      - name: Run backend tests
        run: dotnet test --no-restore --verbosity normal --configuration ${{ matrix.configuration }}