name: PxGraf Frontend SonarScan

run-name: ${{ github.event_name == 'pull_request' &&
  format('Frontend SonarScan for PR {0}', github.event.pull_request.number) || 
  format('Frontend SonarScan for {0}', github.event.head_commit.message) }}

on:
  pull_request:
    branches:
      - 'dev'
  push:
    branches:
      - 'dev'

jobs:
 sonar_frontend:
    permissions: read-all
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'

      - name: Install dependencies
        run: npm ci
        working-directory: ./PxGraf.Frontend

      - name: Test with coverage and generate report
        run: npm run test:ci
        working-directory: ./PxGraf.Frontend

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./PxGraf.Frontend
