name: PxGraf Frontend SonarScan

run-name: ${{ github.event_name == 'pull_request' &&
  format('Frontend SonarScan for PR {0}', github.event.pull_request.number) || 
  format('Frontend SonarScan for {0}', github.event.head_commit.message) }}

on:
  pull_request:
    branches:
      - 'dev'
  push:
    branches:
      - 'dev'

jobs:
 sonar_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Rename sonar properties file 
        run: mv frontend-sonar-project.properties sonar-project.properties
        working-directory: ./pxgraf.frontend

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./PxGraf.Frontend
          args: >
            -D sonar.oranization=statisticsfinland-github
            -D sonar.projectKey=statisticsfinland-github_pxgraf_frontend