name: PxGraf Frontend SonarScan

run-name: ${{ github.event_name == 'pull_request' &&
  format('Frontend SonarScan for PR {0}', github.event.pull_request.number) || 
  format('Frontend SonarScan for {0}', github.event.head_commit.message) }}

on:
  pull_request:
    branches:
      - 'dev'
  push:
    branches:
      - 'dev'

jobs:
 sonar_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install
        working-directory: ./PxGraf.Frontend

      - name: Test with coverage and generate report
        run: npm run test:ci
        working-directory: ./PxGraf.Frontend

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./PxGraf.Frontend
          args: >
            -D sonar.organization=statisticsfinland-github
            -D sonar.projectKey=statisticsfinland-github_pxgraf_frontend
            -D sonar.coverage.lcov.reportPaths=coverage/lcov.info
            -D sonar.testExecutionReportPaths=reports/test-reporter.xml
            -D sonar.sources=PxGraf.Frontend/src
            -D sonar.tests=PxGraf.Frontend/src
            -D sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.test.tsx
            -D sonar.exclusions=**/*.test.js,**/*.test.ts,**/*.test.tsx,**/*.test.tsx.snap
